source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'mobius' do
inherit! :search_paths
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON'
end

target 'mobius-dev' do
inherit! :search_paths
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON'
end

target 'mobius-sim' do
inherit! :search_paths
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON'
end
